apiVersion: apps/v1
kind: Deployment
metadata:
  name: produits-app
  labels:
    app: produits-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : produits-app
  template:
    metadata:
      labels:
        app: produits-app
    spec:
      containers:
      - name: produits-app
        image: sanaeelmadani/mproduit
        imagePullPolicy: Always
        ports:
          - containerPort: 9001

---

kind: Service
apiVersion: v1
metadata:
  name:  produits-app-svc
spec:
  selector:
    app:  produits-app
  ports:
  - port:  80
    targetPort:  9001